// @generated from osiris.grammar — do not edit
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,Version:10, SubGoalCombiner:16, SGC_AND:18, INITSECTION:22, INTEGER:36, INTEGER64:38, REAL:40, STRING:42, GUIDSTRING:44, CHARACTERGUID:46, ITEMGUID:48, TRIGGERGUID:50, CHARACTER:52, ITEM:54, TRIGGER:56, SPLINE:58, LEVELTEMPLATE:60, SPLINEGUID:62, LEVELTEMPLATEGUID:64, KBSECTION:76, IF:80, NOT:84, AND:86, THEN:88, PROC:92, QRY:96, EXITSECTION:100, ENDEXITSECTION:102, ParentTargetEdge:106}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*UQkQPOOQOQPOOQfQPOOQcQPOOQ`QPOOQ]QPOOQYQPOOOrQPO'#C_OwQPO'#CcO|QPO'#CfO!_QPO'#DRO!sQPO'#D_O!{QPO'#DbOOQO,58y,58yOOQO,58},58}O#QQPO'#CiO#VQPO'#ChOOQO'#Dd'#DdO#[QPO,59QOOQO'#Df'#DfO#mQPO,59mO$RQPO'#DTO$ZQPO'#DZO$ZQPO'#D]O$`QPO,59yOOQO,59y,59yOOQO,59|,59|O$hQPO,59TOOQO,59S,59SOOQO-E7b-E7bOOQO-E7d-E7dOOQO'#DV'#DVO$ZQPO'#DVO$yQPO,59oO%RQPO,59uO%ZQPO,59wOOQO1G/e1G/eOOQO'#Cl'#ClO%cQPO'#ClO%nQPO'#CkOOQO1G.o1G.oO%vQPO1G.oO%{QPO'#CmOOQO,59q,59qO&|QPO1G/ZO$RQPO'#DgO$ZQPO1G/ZO'UQPO1G/aO$ZQPO1G/aO'^QPO1G/cO$ZQPO1G/cOOQO,59W,59WO'fQPO'#DeO'tQPO,59VOOQO7+$Z7+$ZO'|QPO,59XOOQO-E7e-E7eO$ZQPO7+$uOOQO,5:R,5:RO(RQPO7+$uO$ZQPO7+${O(jQPO7+${O$ZQPO7+$}O)RQPO7+$}OOQO,5:P,5:POOQO-E7c-E7cOOQO1G.s1G.sO)jQPO<<HaO*RQPO<<HgO*jQPO<<Hi",
  stateData: "+R~O!^OSPOS~OWWOZXOvYO!SZO!V[O~OTVO~PYOU]O~OX^O~OS_OvYX!SYX!VYX![YX~OxeO!OfO!QgO!SuX!VuX![uX~OS_O!TiO~OrjO~O^kO~OtlO~OS_OvYa!SYa!VYa![Ya~OxeO!OfO!QgO!Sua!Vua![ua~OS_OzpO~OS_O~OS_O!TtO~OSuOUuO^zOqxOruO~O{}O|!OO~O{}O|!QO~O{}O|!SO~OS!TOU!TOr!TO~Os!UOq_X~Oq!WO~Ob!XOc!XOd!XOe!XOf!XOg!XOh!XOi!XOj!XOk!XOl!XOm!XOn!XOo!XOp!XO~O{}O|!ZO~O{}O|!^O~O{}O|!`O~OSuOUuO^zOruO~Os!UOq_a~Oq!dO~OS_Oxwq!Owq!Qwq!Swq!Vwq![wq~OS_Ox}q!O}q!Q}q!S}q!V}q![}q~OS_Ox!Pq!O!Pq!Q!Pq!S!Pq!V!Pq![!Pq~OS_Oxwy!Owy!Qwy!Swy!Vwy![wy~OS_Ox}y!O}y!Q}y!S}y!V}y![}y~OS_Ox!Py!O!Py!Q!Py!S!Py!V!Py![!Py~O",
  goto: "%x![PPP!]PPP!`PP!dP!i!{P#l#o#uPPPPPPPPPPPPPPPPPPP#yP$PP$TPPP$PP$PP$ZPP$bP$j%^%d%jRUOTTOUVSOTUqaXZbh!O!Q!S!Z!]!^!_!`!a!e!f!gp`XZbh!O!Q!S!Z!]!^!_!`!a!e!f!gSoe}QrfQsgR{pRykQwkR!b!UTvk!UXROSTUTcYdQqeR![}ZQORSTU]POQRSTUQbXQhZ`mbh!]!_!a!e!f!gQ!]!OQ!_!QQ!a!SQ!e!ZQ!f!^R!g!`Q!VwR!c!VQdYRndQ|qQ!PrQ!RsV!Y|!P!R",
  nodeNames: "⚠ Comment GoalFile VersionDecl Identifier Version Number CombinerDecl SubGoalCombiner SGC_AND InitSection INITSECTION Statement FuncCall ( ArgList Arg TypeCast INTEGER INTEGER64 REAL STRING GUIDSTRING CHARACTERGUID ITEMGUID TRIGGERGUID CHARACTER ITEM TRIGGER SPLINE LEVELTEMPLATE SPLINEGUID LEVELTEMPLATEGUID ) String , ; KbSection KBSECTION Rule IF Condition NOT AND THEN ProcDef PROC QryDef QRY ExitSection EXITSECTION ENDEXITSECTION ParentEdge ParentTargetEdge",
  maxTerm: 60,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "&v~R_XY!QYZ!Q]^!Qpq!Qrs!cxy$Pyz$U|}$Z}!O$`!P!Q%P!Q![$f!]!^%n!c!}%s#R#S%s#T#o%s~!VS!^~XY!QYZ!Q]^!Qpq!Q~!fVOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y<%lO!c~#QOr~~#TRO;'S!c;'S;=`#^;=`O!c~#aWOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y;=`<%l!c<%lO!c~#|P;=`<%l!c~$UO^~~$ZOq~~$`Os~~$cP!Q![$f~$kQU~!O!P$q!Q![$f~$tP!Q![$w~$|PU~!Q![$w~%SP!P!Q%V~%[SP~OY%VZ;'S%V;'S;=`%h<%lO%V~%kP;=`<%l%V~%sOt~~%xTS~}!O&X!Q![%s!c!}%s#R#S%s#T#o%s~&[R!Q![&e!c!}&e#T#o&e~&jSS~}!O&X!Q![&e!c!}&e#T#o&e",
  tokenizers: [0],
  topRules: {"GoalFile":[0,2]},
  specialized: [{term: 4, get: (value: string) => spec_Identifier[value as keyof typeof spec_Identifier] || -1}],
  tokenPrec: 0
})
