// @generated from stats.grammar — do not edit
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_word = {__proto__:null,new:8, entry:10, equipment:12, type:18, using:22, data:26}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#xQYQPOOOOQO'#Cj'#CjQYQPOOO_QPO'#C_OOQO-E6h-E6hOgQPO,58yOlQPO1G.eOOQO'#Ck'#CkO}QPO7+$PO!YQPO'#CdO!_QPO'#CfO!dQPO'#ChO}QPO7+$PO!iQPO7+$POOQO-E6i-E6iOOQO,59O,59OOOQO,59Q,59QO!wQPO,59SO!|QPO<<GkO!|QPO<<GkOOQO1G.n1G.nO#XQPOAN=V",
  stateData: "#d~ObOSPOS~OSRO~OTTOUTO~OVUO~OXXOZYO]ZOSRi`Ri~O]ZOSRq`Rq~OV_O~OV`O~OVaO~OZYO]ZOSRq`Rq~OVdO~O]ZOSRy`Ry~O]ZOSR!R`R!R~O",
  goto: "!^`PPPaPPPPePhPnPw}TPOQR]UQ[URc]_VUW[]bceQQORSQQWUU^WbeSb[]Rec",
  nodeNames: "⚠ LineComment StatsFile StatsEntry new entry equipment String TypeDecl type UsingDecl using DataLine data",
  maxTerm: 19,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "$m~RXXYnYZn]^npqnrs!P!P!Q#m!c!}$[#R#S$[#T#o$[~sSb~XYnYZn]^npqn~!SVOr!Prs!is#O!P#O#P!n#P;'S!P;'S;=`#g<%lO!P~!nOV~~!qRO;'S!P;'S;=`!z;=`O!P~!}WOr!Prs!is#O!P#O#P!n#P;'S!P;'S;=`#g;=`<%l!P<%lO!P~#jP;=`<%l!P~#pP!P!Q#s~#xSP~OY#sZ;'S#s;'S;=`$U<%lO#s~$XP;=`<%l#s~$aSc~!Q![$[!c!}$[#R#S$[#T#o$[",
  tokenizers: [0],
  topRules: {"StatsFile":[0,2]},
  specialized: [{term: 19, get: (value) => spec_word[value] || -1}],
  tokenPrec: 0
})
