// @generated from stats.grammar — do not edit
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  StatsFile = 2,
  StatsEntry = 3,
  _new = 4,
  entry = 5,
  equipment = 6,
  String = 7,
  TypeDecl = 8,
  type = 9,
  UsingDecl = 10,
  using = 11,
  DataLine = 12,
  data = 13
