// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";

/**
 * Represents a detected anchor opportunity.
 */
export type AnchorGroup = { anchor_name: string, shared_changes: Array<Change>, entry_uuids: Array<string>, lines_saved: number, };
