// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of change detected.
 */
export type ChangeType = "StringAdded" | "StringRemoved" | "SelectorAdded" | "SelectorRemoved" | "BooleanChanged" | "FieldChanged" | "ChildAdded" | "ChildRemoved" | "SpellFieldChanged" | "EntireEntryNew";
