// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of converting .lsf and .loca files in the mod destination directory.
 */
export type ConversionResult = { lsf_converted: number, loca_converted: number, 
/**
 * Whether any conversion was needed at all.
 */
needs_conversion: boolean, errors: Array<string>, };
