// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ActionResource metadata used by stats cost editors.
 */
export type CostResourceInfo = { name: string, display_name: string, max_level: number, 
/**
 * Either "resource" or "group".
 */
kind: string, };
