// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateModResult = { project_root: string, mod_root: string, meta_path: string, public_path: string, has_script_extender: boolean, };
