// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of an entry relative to vanilla data.
 */
export type EntryKind = "Modified" | "New";
