// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LsxPreviewEntry } from "./LsxPreviewEntry";

/**
 * A single file to export in a batch mod export operation.
 */
export type ExportFileSpec = { 
/**
 * Absolute path to write the file to.
 */
output_path: string, 
/**
 * LSX region ID (e.g. "Progressions", "Races").
 */
region_id: string, 
/**
 * Entries to serialize into this file.
 */
entries: Array<LsxPreviewEntry>, };
