// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportedFile } from "./ExportedFile";

/**
 * Result of a full mod export operation.
 */
export type ExportModResult = { files: Array<ExportedFile>, errors: Array<string>, file_errors: { [key in string]: Array<string> }, };
