// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of extracting remaining mod files (Localization + meta).
 */
export type ExtractionResult = { 
/**
 * Number of files extracted/copied during this stage.
 */
files_extracted: number, errors: Array<string>, };
