// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about a single list entry and its items.
 */
export type ListItemsInfo = { uuid: string, node_id: string, display_name: string, 
/**
 * The item strings contained in this list (e.g. Spell IDs, Passive IDs).
 */
items: Array<string>, 
/**
 * Which attribute key the items came from (e.g. "Spells", "Passives").
 */
item_key: string, };
