// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single attribute on an LSX node.
 */
export type LsxAttribute = { attr_type: string, value: string, };
