// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single child entry within a child group.
 */
export type LsxChildEntry = { node_id: string, object_guid: string, };
