// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LsxAttribute } from "./LsxAttribute";
import type { LsxChildGroup } from "./LsxChildGroup";

/**
 * Represents a single entry parsed from an LSX file.
 */
export type LsxEntry = { uuid: string, node_id: string, attributes: { [key in string]: LsxAttribute }, children: Array<LsxChildGroup>, 
/**
 * True if this entry was parsed from an XML comment (<!-- ... -->).
 */
commented: boolean, };
