// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry sent from the frontend for LSX preview/export.
 */
export type LsxPreviewEntry = { uuid: string, node_id: string, raw_attributes: { [key in string]?: string }, raw_attribute_types: { [key in string]?: string }, raw_children: { [key in string]?: Array<string> }, };
