// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrSchema } from "./AttrSchema";
import type { ChildSchema } from "./ChildSchema";

/**
 * Complete schema for one LSX node type.
 */
export type NodeSchema = { 
/**
 * The node_id this schema describes (e.g. "Progression", "Race", "God").
 */
node_id: string, 
/**
 * Which Section this node_id belongs to.
 */
section: string, 
/**
 * Total number of vanilla entries sampled.
 */
sample_count: number, 
/**
 * Attribute definitions, sorted by frequency (most common first).
 */
attributes: Array<AttrSchema>, 
/**
 * Child group definitions, sorted by frequency.
 */
children: Array<ChildSchema>, };
