// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of checking whether a mod has relevant Public folder content.
 */
export type RelevanceCheckResult = { 
/**
 * Whether any relevant files were found under Public/.
 */
has_relevant_files: boolean, 
/**
 * Number of relevant files found (for .pak: extracted during check; for dir: counted).
 */
files_found: number, };
