// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModMeta } from "./ModMeta";
import type { SectionResult } from "./SectionResult";

/**
 * Result of scanning a mod folder.
 */
export type ScanResult = { mod_meta: ModMeta, sections: Array<SectionResult>, existing_config_path: string | null, };
