// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChildTableInfo } from "./ChildTableInfo";

/**
 * Describes a data section available in the reference DB.
 * Returned by `cmd_list_available_sections` so the frontend can build its
 * section list dynamically instead of relying on a hardcoded enum.
 */
export type SectionInfo = { 
/**
 * The region ID (e.g. "Races", "CharacterCreationEyeColors").
 */
region_id: string, 
/**
 * Table name in the DB (e.g. "lsx__Races").
 */
table_name: string, 
/**
 * The node ID within the region (may differ from region_id for multi-node regions).
 */
node_id: string, 
/**
 * Source type: "lsx", "stats", "loca", "equipment", "valuelist", "modifier".
 */
source_type: string, 
/**
 * Number of rows in this table.
 */
row_count: number, 
/**
 * Primary key column name (e.g. "UUID", "MapKey", "_entry_name").
 */
pk_column: string, 
/**
 * Child tables linked via junction tables.
 */
children: Array<ChildTableInfo>, };
