// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputFormat } from "./OutputFormat";

/**
 * Options for YAML/JSON serialization.
 */
export type SerializeOptions = { format: OutputFormat, use_anchors: boolean, include_comments: boolean, };
