// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry parsed from a Stats .txt file (Spell_*.txt, Status_*.txt).
 */
export type StatsEntry = { name: string, entry_type: string, parent: string | null, data: { [key in string]: string }, };
