// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight stat entry info for combobox population.
 */
export type StatEntryInfo = { name: string, entry_type: string, };
