// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight entry info for combobox population.
 */
export type VanillaEntryInfo = { uuid: string, display_name: string, 
/**
 * The LSX node_id, e.g. "SpellList", "ActionResourceDefinition".
 */
node_id: string, 
/**
 * Optional hex color value (e.g. "#RRGGBBAA") for color swatch display.
 * Present for ColorDefinition, CharacterCreation color entries, etc.
 */
color: string | null, 
/**
 * Optional parent GUID (e.g. ParentGuid for Race entries).
 */
parent_guid: string | null, 
/**
 * Optional loca handle from a `Text` (TranslatedString) attribute.
 * Present for TooltipExtraTexts, TooltipUpcastDescriptions, etc.
 */
text_handle: string | null, };
